 

codecov:

#token: 47de6975-4cd4-43bc-bb49-db99a50fbb89
#require_ci_to_pass: yes

coverage:

precision: 2

round: down

range: "70...100"

parsers:

gcov:

branch_detection:

conditional: yes

loop: yes

method: no

macro: no

comment:

layout: "reach,diff,flags,files,footer"

behavior: default

require_changes: no

curl --data-binary @- https://codecov.io/validate

$ProgressPreference = 'SilentlyContinue'
Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe 
-Outfile codecov.exe
 .\codecov.exe -t ${47de6975-4cd4-43bc-bb49-db99a50fbb89}
